# Generated by Django 3.0.5 on 2020-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200526_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecalho', models.CharField(max_length=255)),
                ('sequencia', models.TextField()),
                ('tipo', models.CharField(choices=[('dna', 'DNA'), ('rna', 'RNA'), ('proteina', 'PROTEINA')], max_length=8)),
            ],
        ),
    ]
