# Generated by Django 3.0.5 on 2020-05-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_sequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='mSequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fasta', models.FileField(upload_to='sequencias/fasta/')),
                ('tipo', models.CharField(choices=[('dna', 'DNA'), ('rna', 'RNA'), ('proteina', 'PROTEINA')], max_length=8)),
            ],
        ),
    ]
